const SystemInfoKeys = {
  memory: [
    'memoria',
    'ram',
    'memory',
    'memória',
    'disco',
    'armazenamento',
    'armazem',
    'free memory',
    'used memory',
    'memória livre',
    'memória usada',
    'memoria usada',
    'memoria livre',
    'utilização de memória',
    'uso de memória',
    'consumo de memória',
    'memória total',
    'memória disponível',
    'memória física',
    'memória virtual',
    'memória swap',
    'troca de memória',
    'capacidade de memória',
    'memória ocupada',
    'espaço de memória',
    'espaço livre',
    'espaço usado',
    'capacidade total',
    'memória ativa',
    'memória inativa',
    'memória reservada',
    'memória de sistema',
    'memória cache',
    'memória buffer',
    'buffer de memória',
    'cache de memória',
    'memória utilizada',
    'memória não utilizada',
    'uso de RAM',
    'capacidade de RAM',
    'RAM total',
    'RAM disponível',
    'RAM usada',
    'RAM livre',
    'espaço de RAM',
    'espaço de armazenamento',
    'armazenamento livre',
    'armazenamento usado',
    'capacidade de armazenamento',
    'espaço disponível',
    'espaço ocupado',
    'capacidade total de armazenamento',
    'memória do sistema',
    'uso do sistema',
    'memória de vídeo',
    'memória gráfica',
    'memória GPU',
    'memória de vídeo disponível',
    'memória gráfica usada'
  ],
  cpuUsage: [
    'cpu',
    'processador',
    'uso',
    'consumo',
    'gastando',
    'processo',
    'proccess',
    'utilização da cpu',
    'uso da cpu',
    'cpu usage',
    'uso do processador',
    'consumo da cpu',
    'consumo do processador',
    'cpu load',
    'load da cpu',
    'carga da cpu',
    'carga do processador',
    'utilização do processador',
    'utilização do núcleo',
    'núcleo da cpu',
    'núcleo do processador',
    'cpu cores',
    'processador cores',
    'frequência da cpu',
    'frequência do processador',
    'velocidade da cpu',
    'velocidade do processador',
    'cpu speed',
    'processador speed',
    'temperatura da cpu',
    'temperatura do processador',
    'cpu temperature',
    'processador temperature',
    'uso de cpu',
    'uso de processador',
    'consumo de cpu',
    'consumo de processador',
    'uso de núcleo',
    'uso de cores',
    'carga de núcleo',
    'carga de cores',
    'cpu performance',
    'processador performance',
    'desempenho da cpu',
    'desempenho do processador',
    'cpu efficiency',
    'processador efficiency',
    'eficiência da cpu',
    'eficiência do processador',
    'cpu utilization',
    'processador utilization',
    'uso de recursos da cpu',
    'uso de recursos do processador',
    'recursos da cpu',
    'recursos do processador'
  ],
  apps: [
    'aplicativos',
    'apps',
    'instalado',
    'baixado',
    'tenho',
    'programas',
    'softwares',
    'aplicações',
    'aplicativos instalados',
    'programas instalados',
    'softwares instalados',
    'aplicações instaladas',
    'aplicativos baixados',
    'programas baixados',
    'softwares baixados',
    'aplicações baixadas',
    'lista de aplicativos',
    'lista de programas',
    'lista de softwares',
    'lista de aplicações',
    'aplicativos em execução',
    'programas em execução',
    'softwares em execução',
    'aplicações em execução',
    'aplicativos rodando',
    'programas rodando',
    'softwares rodando',
    'aplicações rodando',
    'apps instalados',
    'apps baixados',
    'apps em execução',
    'apps rodando',
    'aplicativos instalados recentemente',
    'programas instalados recentemente',
    'softwares instalados recentemente',
    'aplicações instaladas recentemente',
    'apps instalados recentemente',
    'aplicativos mais usados',
    'programas mais usados',
    'softwares mais usados',
    'aplicações mais usadas',
    'apps mais usados',
    'aplicativos populares',
    'programas populares',
    'softwares populares',
    'aplicações populares',
    'apps populares',
    'aplicativos novos',
    'programas novos',
    'softwares novos',
    'aplicações novas',
    'apps novos',
    'aplicativos favoritos',
    'programas favoritos',
    'softwares favoritos',
    'aplicações favoritas',
    'apps favoritos'
  ],
  processes: [
    'aplicativos',
    'apps',
    'instalado',
    'baixado',
    'tenho',
    'processo',
    'processador',
    'execução',
    'processos em execução',
    'executando',
    'process list',
    'lista de processos',
    'processos ativos',
    'processos rodando',
    'processos do sistema',
    'processos do usuário',
    'processos em segundo plano',
    'processos de fundo',
    'background processes',
    'foreground processes',
    'processos principais',
    'processos secundários',
    'processos críticos',
    'processos não críticos',
    'processos prioritários',
    'processos não prioritários',
    'processos importantes',
    'processos não importantes',
    'processos essenciais',
    'processos não essenciais',
    'processos do sistema operacional',
    'processos do OS',
    'processos do sistema operacional',
    'processos do Windows',
    'processos do MacOS',
    'processos do Linux',
    'processos do Ubuntu',
    'processos do Fedora',
    'processos do Debian',
    'processos do CentOS',
    'processos do Arch',
    'processos do Manjaro',
    'processos do Gentoo',
    'processos do Solaris',
    'processos do FreeBSD',
    'processos do NetBSD',
    'processos do OpenBSD',
    'processos do Android',
    'processos do iOS',
    'processos do Unix',
    'processos do BSD',
    'processos do DOS',
    'processos do ChromeOS',
    'processos do Haiku',
    'processos do ReactOS',
    'processos do Raspbian',
    'processos do OpenSUSE',
    'processos do Mageia',
    'processos do Mandriva',
    'processos do Slackware',
    'processos do ZorinOS'
  ],
  mainboard: [
    'placa mãe',
    'hardware',
    'pc',
    'placa',
    'mãe',
    'informações',
    'informações da placa mãe',
    'informações do hardware',
    'informações do pc',
    'motherboard',
    'mainboard info',
    'detalhes da placa mãe',
    'detalhes do hardware',
    'detalhes do pc',
    'specs da placa mãe',
    'especificações da placa mãe',
    'especificações do hardware',
    'especificações do pc',
    'marca da placa mãe',
    'modelo da placa mãe',
    'versão da placa mãe',
    'serial da placa mãe',
    'fabricante da placa mãe',
    'informações da motherboard',
    'informações da mainboard',
    'detalhes da motherboard',
    'detalhes da mainboard',
    'specs da motherboard',
    'especificações da motherboard',
    'marca da motherboard',
    'modelo da motherboard',
    'versão da motherboard',
    'serial da motherboard',
    'fabricante da motherboard',
    'placa mãe do sistema',
    'motherboard do sistema',
    'mainboard do sistema',
    'detalhes da mainboard',
    'specs da mainboard',
    'especificações da mainboard',
    'marca da mainboard',
    'modelo da mainboard',
    'versão da mainboard',
    'serial da mainboard',
    'fabricante da mainboard',
    'informações da placa principal',
    'detalhes da placa principal',
    'specs da placa principal',
    'especificações da placa principal',
    'marca da placa principal',
    'modelo da placa principal',
    'versão da placa principal',
    'serial da placa principal',
    'fabricante da placa principal',
    'informações da board',
    'detalhes da board',
    'specs da board',
    'especificações da board',
    'marca da board',
    'modelo da board',
    'versão da board',
    'serial da board',
    'fabricante da board',
    'detalhes do motherboard',
    'detalhes do mainboard',
    'detalhes do board',
    'detalhes da board',
    'detalhes do sistema de hardware',
    'detalhes do sistema de motherboard',
    'detalhes do sistema de mainboard',
    'detalhes do sistema de board',
    'detalhes do sistema de hardware'
  ],
  packageManager: [
    'npm',
    'yarn',
    'pnpm',
    'apps',
    'pacotes',
    'packet',
    'packets',
    'instalado',
    'gestor de pacotes',
    'gerenciador de pacotes',
    'pacotes npm',
    'pacotes yarn',
    'pacotes pnpm',
    'pacotes instalados',
    'lista de pacotes',
    'packages',
    'installed packages',
    'pacotes em execução',
    'pacotes rodando',
    'gestores de pacotes',
    'gerenciadores de pacotes',
    'npm packages',
    'yarn packages',
    'pnpm packages',
    'pacotes npm instalados',
    'pacotes yarn instalados',
    'pacotes pnpm instalados',
    'pacotes npm rodando',
    'pacotes yarn rodando',
    'pacotes pnpm rodando',
    'npm package manager',
    'yarn package manager',
    'pnpm package manager',
    'npm packages list',
    'yarn packages list',
    'pnpm packages list',
    'npm installed packages',
    'yarn installed packages',
    'pnpm installed packages',
    'npm running packages',
    'yarn running packages',
    'pnpm running packages',
    'npm gestor de pacotes',
    'yarn gestor de pacotes',
    'pnpm gestor de pacotes',
    'npm gerenciador de pacotes',
    'yarn gerenciador de pacotes',
    'pnpm gerenciador de pacotes',
    'npm pacotes instalados',
    'yarn pacotes instalados',
    'pnpm pacotes instalados',
    'npm pacotes rodando',
    'yarn pacotes rodando',
    'pnpm pacotes rodando',
    'npm package manager info',
    'yarn package manager info',
    'pnpm package manager info',
    'npm packages info',
    'yarn packages info',
    'pnpm packages info',
    'npm installed packages info',
    'yarn installed packages info',
    'pnpm installed packages info',
    'npm running packages info',
    'yarn running packages info',
    'pnpm running packages info'
  ],
  cpuInfo: [
    'cpu',
    'processador',
    'uso',
    'consumo',
    'gastando',
    'processos',
    'proccess',
    'informações da cpu',
    'detalhes da cpu',
    'cpu details',
    'informações do processador',
    'cpu specs',
    'especificações da cpu',
    'detalhes do processador',
    'processador specs',
    'processador specifications',
    'cpu specifications',
    'marca da cpu',
    'modelo da cpu',
    'versão da cpu',
    'serial da cpu',
    'fabricante da cpu',
    'marca do processador',
    'modelo do processador',
    'versão do processador',
    'serial do processador',
    'fabricante do processador',
    'cpu do sistema',
    'processador do sistema',
    'detalhes do cpu',
    'detalhes do processador',
    'detalhes do sistema',
    'detalhes do cpu do sistema',
    'detalhes do processador do sistema',
    'cpu usage info',
    'processador usage info',
    'cpu performance info',
    'processador performance info',
    'cpu efficiency info',
    'processador efficiency info',
    'cpu utilization info',
    'processador utilization info',
    'cpu resources info',
    'processador resources info',
    'cpu cores info',
    'processador cores info',
    'cpu speed info',
    'processador speed info',
    'cpu temperature info',
    'processador temperature info',
    'cpu load info',
    'processador load info',
    'cpu load details',
    'processador load details',
    'cpu usage details',
    'processador usage details',
    'cpu performance details',
    'processador performance details',
    'cpu efficiency details',
    'processador efficiency details',
    'cpu utilization details',
    'processador utilization details',
    'cpu resources details',
    'processador resources details',
    'cpu cores details',
    'processador cores details',
    'cpu speed details',
    'processador speed details',
    'cpu temperature details',
    'processador temperature details'
  ],
  osInfo: [
    'si',
    'os',
    'sistema',
    'operacional',
    'sistema operacional',
    'informações do sistema',
    'detalhes do sistema',
    'os info',
    'sistema info',
    'operating system',
    'system details',
    'informações do sistema operacional',
    'detalhes do sistema operacional',
    'os details',
    'sistema operacional info',
    'detalhes do sistema operacional',
    'os version',
    'sistema operacional version',
    'versão do sistema operacional',
    'os specs',
    'sistema operacional specs',
    'especificações do sistema operacional',
    'os specifications',
    'os specifications',
    'informações do sistema',
    'detalhes do sistema',
    'os manufacturer',
    'fabricante do sistema operacional',
    'os developer',
    'desenvolvedor do sistema operacional',
    'os type',
    'tipo do sistema operacional',
    'os architecture',
    'arquitetura do sistema operacional',
    'os kernel',
    'kernel do sistema operacional',
    'os build',
    'build do sistema operacional',
    'os release',
    'release do sistema operacional',
    'os build number',
    'número do build do sistema operacional',
    'os release number',
    'número do release do sistema operacional',
    'os release date',
    'data do release do sistema operacional',
    'os end of support',
    'fim do suporte do sistema operacional',
    'os support',
    'suporte do sistema operacional',
    'os update',
    'atualização do sistema operacional',
    'os patches',
    'patches do sistema operacional',
    'os upgrades',
    'upgrades do sistema operacional',
    'os features',
    'funcionalidades do sistema operacional',
    'os capabilities',
    'capacidades do sistema operacional',
    'os requirements',
    'requisitos do sistema operacional'
  ],
  network: [
    'rede',
    'net',
    'internet',
    'wifi',
    'conexão',
    'network',
    'informações da rede',
    'detalhes da rede',
    'network info',
    'informações da conexão',
    'detalhes da conexão',
    'network details',
    'internet info',
    'wifi info',
    'network status',
    'status da rede',
    'estado da rede',
    'status da conexão',
    'estado da conexão',
    'informações da wifi',
    'detalhes da wifi',
    'wifi status',
    'estado da wifi',
    'internet connection',
    'conexão de internet',
    'estado da internet',
    'informações da internet',
    'internet details',
    'informações da rede',
    'estado da conexão de internet',
    'status da conexão de internet',
    'detalhes da conexão de internet',
    'estado da wifi',
    'informações da conexão de wifi',
    'detalhes da conexão de wifi',
    'informações da rede local',
    'detalhes da rede local',
    'status da rede local',
    'estado da rede local',
    'informações da LAN',
    'detalhes da LAN',
    'estado da LAN',
    'status da LAN',
    'informações da WAN',
    'detalhes da WAN',
    'estado da WAN',
    'status da WAN',
    'informações da rede privada',
    'detalhes da rede privada',
    'estado da rede privada',
    'status da rede privada',
    'informações da rede pública',
    'detalhes da rede pública',
    'estado da rede pública',
    'status da rede pública',
    'informações da rede de dados',
    'detalhes da rede de dados',
    'estado da rede de dados',
    'status da rede de dados',
    'informações da rede móvel',
    'detalhes da rede móvel',
    'estado da rede móvel',
    'status da rede móvel',
    'informações da rede sem fio',
    'detalhes da rede sem fio',
    'estado da rede sem fio',
    'status da rede sem fio',
    'informações da rede com fio',
    'detalhes da rede com fio',
    'estado da rede com fio',
    'status da rede com fio',
    'informações da rede ethernet',
    'detalhes da rede ethernet',
    'estado da rede ethernet',
    'status da rede ethernet',
    'informações da rede VPN',
    'detalhes da rede VPN',
    'estado da rede VPN',
    'status da rede VPN',
    'informações da conexão de rede',
    'detalhes da conexão de rede',
    'estado da conexão de rede',
    'status da conexão de rede',
    'informações do adaptador de rede',
    'detalhes do adaptador de rede',
    'estado do adaptador de rede',
    'status do adaptador de rede',
    'informações do ponto de acesso',
    'detalhes do ponto de acesso',
    'estado do ponto de acesso',
    'status do ponto de acesso',
    'informações do roteador',
    'detalhes do roteador',
    'estado do roteador',
    'status do roteador',
    'informações do modem',
    'detalhes do modem',
    'estado do modem',
    'status do modem'
  ],
  battery: [
    'bateria',
    'porcento',
    'procentagem',
    'energia',
    'nível da bateria',
    'battery',
    'informações da bateria',
    'detalhes da bateria',
    'battery info',
    'battery details',
    'battery percentage',
    'battery level',
    'estado da bateria',
    'status da bateria',
    'informações de energia',
    'detalhes de energia',
    'energy info',
    'energy details',
    'energy percentage',
    'energy level',
    'estado de energia',
    'status de energia',
    'informações da carga',
    'detalhes da carga',
    'charging info',
    'charging details',
    'charging percentage',
    'charging level',
    'estado da carga',
    'status da carga',
    'informações da descarga',
    'detalhes da descarga',
    'discharging info',
    'discharging details',
    'discharging percentage',
    'discharging level',
    'estado da descarga',
    'status da descarga',
    'informações da capacidade',
    'detalhes da capacidade',
    'capacity info',
    'capacity details',
    'capacity percentage',
    'capacity level',
    'estado da capacidade',
    'status da capacidade',
    'informações da saúde da bateria',
    'detalhes da saúde da bateria',
    'battery health info',
    'battery health details',
    'battery health percentage',
    'battery health level',
    'estado da saúde da bateria',
    'status da saúde da bateria',
    'informações do tempo de bateria',
    'detalhes do tempo de bateria',
    'battery time info',
    'battery time details',
    'battery time percentage',
    'battery time level',
    'estado do tempo de bateria',
    'status do tempo de bateria',
    'informações do tempo de carga',
    'detalhes do tempo de carga',
    'charging time info',
    'charging time details',
    'charging time percentage',
    'charging time level',
    'estado do tempo de carga',
    'status do tempo de carga',
    'informações do tempo de descarga',
    'detalhes do tempo de descarga',
    'discharging time info',
    'discharging time details',
    'discharging time percentage',
    'discharging time level',
    'estado do tempo de descarga',
    'status do tempo de descarga',
    'informações do ciclo de carga',
    'detalhes do ciclo de carga',
    'charging cycle info',
    'charging cycle details',
    'charging cycle percentage',
    'charging cycle level',
    'estado do ciclo de carga',
    'status do ciclo de carga',
    'informações do ciclo de descarga',
    'detalhes do ciclo de descarga',
    'discharging cycle info',
    'discharging cycle details',
    'discharging cycle percentage',
    'discharging cycle level',
    'estado do ciclo de descarga',
    'status do ciclo de descarga',
    'informações do tempo de uso',
    'detalhes do tempo de uso',
    'usage time info',
    'usage time details',
    'usage time percentage',
    'usage time level',
    'estado do tempo de uso',
    'status do tempo de uso'
  ],
  disk: [
    'disco',
    'armazenamento',
    'storage',
    'informações do disco',
    'detalhes do disco',
    'informações do armazenamento',
    'detalhes do armazenamento',
    'estado do disco',
    'estado do armazenamento',
    'status do disco',
    'status do armazenamento',
    'capacidade do disco',
    'capacidade do armazenamento',
    'uso do disco',
    'uso do armazenamento',
    'livre no disco',
    'livre no armazenamento',
    'disponível no disco',
    'disponível no armazenamento',
    'espaço livre no disco',
    'espaço livre no armazenamento',
    'espaço usado no disco',
    'espaço usado no armazenamento',
    'espaço total do disco',
    'espaço total do armazenamento',
    'espaço restante no disco',
    'espaço restante no armazenamento',
    'uso de espaço no disco',
    'uso de espaço no armazenamento',
    'detalhes do espaço no disco',
    'detalhes do espaço no armazenamento',
    'informações de espaço no disco',
    'informações de espaço no armazenamento',
    'estado do espaço no disco',
    'estado do espaço no armazenamento',
    'status do espaço no disco',
    'status do espaço no armazenamento',
    'detalhes da partição do disco',
    'detalhes da partição do armazenamento',
    'informações da partição do disco',
    'informações da partição do armazenamento',
    'partições do disco',
    'partições do armazenamento',
    'informações do particionamento do disco',
    'informações do particionamento do armazenamento',
    'detalhes do particionamento do disco',
    'detalhes do particionamento do armazenamento',
    'espaço da partição do disco',
    'espaço da partição do armazenamento',
    'detalhes da utilização do disco',
    'detalhes da utilização do armazenamento',
    'informações da utilização do disco',
    'informações da utilização do armazenamento',
    'estado da utilização do disco',
    'estado da utilização do armazenamento',
    'status da utilização do disco',
    'status da utilização do armazenamento',
    'informações do sistema de arquivos',
    'detalhes do sistema de arquivos',
    'estado do sistema de arquivos',
    'status do sistema de arquivos',
    'informações do tipo de sistema de arquivos',
    'detalhes do tipo de sistema de arquivos',
    'tipo de sistema de arquivos',
    'sistema de arquivos',
    'file system',
    'file system type',
    'file system info',
    'file system details',
    'disk partitions',
    'storage partitions',
    'disk usage',
    'storage usage',
    'disk space',
    'storage space',
    'disk capacity',
    'storage capacity',
    'disk free space',
    'storage free space',
    'disk used space',
    'storage used space',
    'disk available space',
    'storage available space',
    'disk total space',
    'storage total space',
    'disk remaining space',
    'storage remaining space',
    'disk partition info',
    'storage partition info',
    'disk partition details',
    'storage partition details',
    'disk usage info',
    'storage usage info',
    'disk usage details',
    'storage usage details'
  ],
  users: [
    'usuários',
    'users',
    'pessoas',
    'informações dos usuários',
    'detalhes dos usuários',
    'informações das pessoas',
    'detalhes das pessoas',
    'estado dos usuários',
    'estado das pessoas',
    'status dos usuários',
    'status das pessoas',
    'usuários conectados',
    'usuários logados',
    'usuários logados no sistema',
    'usuários conectados no sistema',
    'usuários ativos',
    'usuários ativos no sistema',
    'informações dos usuários conectados',
    'informações dos usuários logados',
    'detalhes dos usuários conectados',
    'detalhes dos usuários logados',
    'estado dos usuários conectados',
    'estado dos usuários logados',
    'status dos usuários conectados',
    'status dos usuários logados',
    'usuários atuais',
    'usuários atuais no sistema',
    'informações dos usuários atuais',
    'detalhes dos usuários atuais',
    'estado dos usuários atuais',
    'status dos usuários atuais',
    'informações das contas de usuário',
    'detalhes das contas de usuário',
    'estado das contas de usuário',
    'status das contas de usuário',
    'informações dos perfis de usuário',
    'detalhes dos perfis de usuário',
    'estado dos perfis de usuário',
    'status dos perfis de usuário',
    'usuários do sistema',
    'pessoas do sistema',
    'informações dos usuários do sistema',
    'detalhes dos usuários do sistema',
    'estado dos usuários do sistema',
    'status dos usuários do sistema',
    'usuários do computador',
    'usuários do pc',
    'informações dos usuários do computador',
    'detalhes dos usuários do computador',
    'estado dos usuários do computador',
    'status dos usuários do computador',
    'informações dos usuários do pc',
    'detalhes dos usuários do pc',
    'estado dos usuários do pc',
    'status dos usuários do pc',
    'usuários do dispositivo',
    'informações dos usuários do dispositivo',
    'detalhes dos usuários do dispositivo',
    'estado dos usuários do dispositivo',
    'status dos usuários do dispositivo',
    'usuários na máquina',
    'usuários na máquina atual',
    'usuários na máquina do sistema',
    'informações dos usuários na máquina',
    'detalhes dos usuários na máquina',
    'estado dos usuários na máquina',
    'status dos usuários na máquina',
    'usuários na máquina atual',
    'usuários na máquina do sistema',
    'usuários na máquina do computador',
    'usuários na máquina do pc',
    'informações dos usuários na máquina do computador',
    'detalhes dos usuários na máquina do computador',
    'estado dos usuários na máquina do computador',
    'status dos usuários na máquina do computador',
    'informações dos usuários na máquina do pc',
    'detalhes dos usuários na máquina do pc',
    'estado dos usuários na máquina do pc',
    'status dos usuários na máquina do pc',
    'informações dos usuários na máquina do dispositivo',
    'detalhes dos usuários na máquina do dispositivo',
    'estado dos usuários na máquina do dispositivo',
    'status dos usuários na máquina do dispositivo',
    'usuários do sistema operacional',
    'usuários do OS',
    'informações dos usuários do sistema operacional',
    'detalhes dos usuários do sistema operacional',
    'estado dos usuários do sistema operacional',
    'status dos usuários do sistema operacional',
    'informações dos usuários do OS',
    'detalhes dos usuários do OS',
    'estado dos usuários do OS',
    'status dos usuários do OS',
    'usuários do sistema operacional atual',
    'usuários do OS atual',
    'informações dos usuários do sistema operacional atual',
    'detalhes dos usuários do sistema operacional atual',
    'estado dos usuários do sistema operacional atual',
    'status dos usuários do sistema operacional atual',
    'informações dos usuários do OS atual',
    'detalhes dos usuários do OS atual',
    'estado dos usuários do OS atual',
    'status dos usuários do OS atual'
  ],
  gpu: [
    'gpu',
    'placa de vídeo',
    'placa de video',
    'placa gráfica',
    'video card',
    'graphics card',
    'informações da gpu',
    'detalhes da gpu',
    'gpu info',
    'gpu details',
    'estado da gpu',
    'status da gpu',
    'informações da placa de vídeo',
    'detalhes da placa de vídeo',
    'estado da placa de vídeo',
    'status da placa de vídeo',
    'informações da placa de video',
    'detalhes da placa de video',
    'estado da placa de video',
    'status da placa de video',
    'informações da placa gráfica',
    'detalhes da placa gráfica',
    'estado da placa gráfica',
    'status da placa gráfica',
    'gpu performance',
    'performance da gpu',
    'gpu performance info',
    'gpu performance details',
    'detalhes da performance da gpu',
    'estado da performance da gpu',
    'status da performance da gpu',
    'gpu usage',
    'uso da gpu',
    'gpu usage info',
    'gpu usage details',
    'detalhes do uso da gpu',
    'estado do uso da gpu',
    'status do uso da gpu',
    'gpu temperature',
    'temperatura da gpu',
    'gpu temperature info',
    'gpu temperature details',
    'detalhes da temperatura da gpu',
    'estado da temperatura da gpu',
    'status da temperatura da gpu',
    'gpu memory',
    'memória da gpu',
    'gpu memory info',
    'gpu memory details',
    'detalhes da memória da gpu',
    'estado da memória da gpu',
    'status da memória da gpu',
    'gpu specs',
    'especificações da gpu',
    'gpu specifications',
    'detalhes das especificações da gpu',
    'estado das especificações da gpu',
    'status das especificações da gpu',
    'gpu manufacturer'
  ]
}

export default SystemInfoKeys
